# https://www.jeffastor.com/blog/pairing-a-postgresql-db-with-your-dockerized-fastapi-app
version: '3.9'
services:
  bulk-api:
    container_name: bulkapi-container
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    #enviroment part not working -- ??
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUBBUFFERED: 1
      WORKING_DATABASE_URL: postgres://postgres:postgres@postgres_14_2_alpine:5432/postgres
      ENABLE_ERROR_LOG_DUMP: 1
      ENABLE_EXTENDED_VALIDATION_ERROR_LOG_DUMP: 1
      ENABLE_SUCCESS_LOG_DUMP: 1
      #ALLOWED_HOST: "172.16.31.118,172.16.31.125,172.18.57.225,172.16.23.200"
      ALLOWED_HOST: "172.16.31.118,172.16.31.125,172.18.57.225,172.16.23.200,172.16.23.237,172.16.67.208,172.16.66.100,172.16.23.169,192.168.2.82,192.168.2.95,31.220.109.83"
      API_USER_KEY: "sym=1234,SymIT=BWdzrpia0sNXd49,AmdrGroBzr=02pAHN9sCYT1"
    command: ["uvicorn", "bulkApi:app", "--host", "0.0.0.0", "--port", "7000"]
    ports:
      - 7000:7000
    networks:
      - postgres_default

networks:
  postgres_default:
    external: true

